// ⚠️ 此文件由脚本自动生成，请勿手动修改
// 生成时间: 2026-06-19T13:18:54.218Z

export const SVG_PATH_NAMES = [
  'affiliate',
  'arrow_down',
  'arrow_left',
  'arrow_long_left',
  'arrow_long_right',
  'arrow_right',
  'arrow_up',
  'bonus',
  'bottom_acting',
  'bottom_casino',
  'bottom_home',
  'bottom_sports',
  'bottom_user',
  'bottom_vip2',
  'cart',
  'choose_off',
  'choose_on',
  'close',
  'copy',
  'edit',
  'favorites',
  'file',
  'glass-border',
  'globe',
  'help',
  'home',
  'hot',
  'menu',
  'message',
  'next',
  'order',
  'profile',
  'promotion',
  'recent',
  'search',
  'service',
  'settings',
  'time',
  'tips_correct',
  'tips_error',
  'tips_system',
  'tips_warning',
  'tournament',
  'truco',
  'vip',
  'window',
] as const;

export type SvgPathName = (typeof SVG_PATH_NAMES)[number];
