// src/app/[locale]/layout.tsx
import type { Metadata, Viewport } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';

import '@/app/globals.css';
import ClientInitializer from '@/components/features/ClientInitializer';
import RouteModalRenderer from '@/components/features/RouteModalRenderer';
import { DialogProvider } from '@/components/ui/Dialog';
import { getBrandConfigSSR } from '@/libs/brand';
import { cn } from '@/libs/class-helpers';
import { geistMono } from '@/libs/fonts';
import { BrandConfigProvider } from '@/providers/brand.provider';

export const runtime = 'edge';
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
};
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  console.log('__LocaleLayout__');
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  // if (!hasLocale(routing.locales, locale)) {
  //   notFound();
  // }

  // Enable static rendering
  setRequestLocale(locale);

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  // 获取品牌配置
  const brandConfig = await getBrandConfigSSR();

  return (
    <html lang={locale}>
      <body className={cn('antialiased', geistMono.variable)}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <BrandConfigProvider value={brandConfig}>
            <DialogProvider>
              {children}
              <RouteModalRenderer />
              <ClientInitializer />
            </DialogProvider>
          </BrandConfigProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
